# Sample workflow for building and deploying a Hello World deployment to GitHub Pages
# Go to Settings -> Pages -> Build and deployment -> Set the Source to "Github Actions".
name: Build & Deploy site to GH Pages


# Will fire when a new release is published
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  # Automated Deployments
  workflow_call:
  release:
    types: [published]
  # push:
  #   tags: [v*]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write
  pages: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  validate_actor:
    uses: crajapakshe/devops-tools/.github/workflows/is_authorized_user.yml@main

  build: 
    runs-on: ubuntu-latest
    needs: validate_actor
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEVOPS_PAT }}
          publish_dir: ./  

  deploy:
    environment:
      name: dev
      url: ${{ steps.deployment.outputs.page_url }} # https://<username>.github.io/<repo>
    runs-on: ubuntu-latest # runner
    needs: build # only do this if the build was succesfull
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4