name: Docker Image CI (Test)

on:
  workflow_call:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build the Docker Test image
        run: docker build . --file Dockerfile --tag crajapakshe429/docker-helloworld:latest

      - name: Run Docker container
        run: docker run -d -p 8080:80 --name docker-helloworld-container crajapakshe429/docker-helloworld:latest

      - name: Wait for container to be ready
        run: sleep 10  # Adjust the sleep time as needed

      - name: Test Docker container
        run: |
          docker ps  # List running containers
          curl -f http://localhost:8080  # Test Nginx server

      - name: Stop and remove Docker container
        run: |
          docker stop docker-helloworld-container
          docker rm docker-helloworld-container